### PR TITLE
Fix #93

### LINKED ISSUE #93: sizeof(...) translation fails if part of complex constexpr
This fail:

```c++
constexpr int blah() { return 0; }
constexpr int i = sizeof(int) + blah() + sizeof(int);
```

### PR DESCRIPTION
**Pull request by trikko**
Fix for bug #93

### CODE REVIEW

**Comment by atilaneves** [comment]
Please write a test. See tests/it/issues.d

**Comment by trikko** [comment]
Not sure how it works your testsuite.
Test is in bug #93 :)

**Comment by atilaneves** [comment]
Then: 

```d
@("93")
@safe unittest {
    shouldCompile(
        Cpp(
            q{
                constexpr int blah() { return 0; }
                constexpr int i = sizeof(int) + blah() + sizeof(int);
            }
        ),
        D(
            q{
            }
        ),
    );
}
```

Assuming that just trying to translate the C++ code didn't work.

**Comment by trikko** [comment]
Ok, I realized that I can simply add a parens before sizeof, so now test works.

**Pull request merged**
