### PR TITLE
Windows support.

### PR DESCRIPTION
**Pull request by veelo**
Fixes issues #80 and #86.

Just a trivial `dub` change and build instructions. The real change is in `libclang`, so please bump its version and update dub dependencies.

Cheers,
Bastiaan.

### CODE REVIEW

**Comment by atilaneves** [comment]
I'm surprised you didn't have to change the call to the preprocessor to make this work on Windows.

**Comment by veelo** [comment]
> I'm surprised you didn't have to change the call to the preprocessor to make this work on Windows.

I might have to, because the header that I am including is not yet being translated well. Where can I find that call?

**Comment by veelo** [comment]
By the way, I see no `cpp.exe` in the `bin` directory of LLVM on Windows, only `clang-cpp.exe`.

**Comment by veelo** [comment]
After uninstalling FPC I get indeed the `Failed to spawn new process` error without context. I'll update this PR with `try`/`catch` like I did with libclang. I think I'll also have to call `clang-cpp` instead of just `cpp`. Is that something that will work on Posix as well, or should I `version` that out?

**Comment by atilaneves** [comment]
I don't know about depending on clang-cpp. It's installed on my system because I assume it's a clang dependency. But it might just be that there are people who install libclang and don't have clang-cpp? I don't know. I'd probably version it out just in case.

**Comment by veelo** [comment]
I have a similar check around `execute` in `runtime.app.run()` ready, but I am reluctant to commit because it is unlikely that `dmd` is not in the path. I am starting to think that the real problem is that the exception that is being thrown on Windows lacks the detailed information that is present on Linux at least (std.process.ProcessException@std/process.d(380): Executable file not found: blah). If that would have been the case I probably would not have bothered, and you could have done without this extra code noise...

What probably /would/ need a similar check nonetheless is `compileSrcFile`. Otherwise, if `g++` is not present, it will throw and `clang++` won't be tried. I have not added this test though because in my case that code seems never to be executed.

**Comment by veelo** [comment]
Thanks!

**Pull request merged**
