### PR TITLE
Made this code cleaned up and more generic to ignore headers

### PR DESCRIPTION
**Pull request by adamdruppe**
It isn't the best UI but it avoids hardcoding long lists of files.

### CODE REVIEW

**Comment by atilaneves** [comment]
Looks good other than not having tests. You can test command-line arguments, a good example is [here](https://github.com/atilaneves/dpp/blob/a4139775eb029591b8f7f509c65d1e98ee85bba2/tests/it/cpp/opaque.d#L38).

**Comment by adamdruppe** [comment]
there we go had to add three but they worked. kinda weird tests but static assert was good enough

**Comment by atilaneves** [comment]
> there we go had to add three but they worked. kinda weird tests but static assert was good enough

static asserts are preferred ;)

**Comment by adamdruppe** [comment]
i also updated my mondo fork PR to use these new options btw. gets that 6 min build on Windows without hacks (it took a lot of hacks and experiments to get the PR this clean lol)

**Comment by atilaneves** [comment]
I still haven't been able to update dpp to the fastest version. Try again tomorrow when there's a new tag and you might be pleasantly surprised ;)

**Pull request merged**
